bboard/application/urls.py
from django.urls import path

from .views import *

app_name = 'application'


urlpatterns = [
   path('application/create', CreateApplicationView.as_view(), name='create'),
   path('application/delete/<int:pk>', DeleteApplication.as_view(), name='delete'),
   path('application/change_status/<int:pk>', ChangeStatusView.as_view(), name='change_status'),

   path('category', IndexCategory.as_view(), name='index_category'),
   path('category/delete/<int:pk>', DeleteCategory.as_view(), name='delete_category'),
   path('category/create', CreateCategory.as_view(), name='create_category'),
]

bboard/main/urls.py
from django.urls import path

from .views import index, other_page

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('<str:page>/', other_page, name='other'),
]

bboard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
    path('', include('user.urls', namespace=''))
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/user/urls.py
from django.urls import path

from .views import *

app_name = 'user'

urlpatterns = [
   path('accounts/login', BBLoginView.as_view(), name='login'),
   path('accounts/profile/', profile, name='profile'),
   path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
   path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
   path('accounts/register/', RegisterUserView.as_view(), name='register'),
   path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
]

main/urls.py
from django.urls import path

from .views import index, other_page

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('<str:page>/', other_page, name='other'),
]

bboard/application/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

from user.models import AdvUser


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')

    def __str__(self):
        return self.name


class Application(models.Model):
    STATUSES = [
        ('new', 'Новая'),
        ('in_work', 'В работе'),
        ('complete', 'Выполнено')
    ]

    user = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Создатель')
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    image = models.ImageField(verbose_name='Изображение', upload_to='application_image',
                              validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])],
                              blank=True)
    status = models.CharField(max_length=15, choices=STATUSES, default=STATUSES[0][0], verbose_name='Статус')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    text = models.TextField(verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.title

bboard/main/models.py
from django.db import models

# Create your models here.

bboard/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal

from .utilities import send_activation_notification

user_registrated = Signal('instance')


def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispatcher)


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True,
                                        verbose_name='Оповещать при новых комментариях?')

    class Meta(AbstractUser.Meta):
        pass

bboard/application/forms.py
from django import forms

from .models import Application, Category


class CreateApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ('title', 'text', 'image', 'category',)


class ChangeStatusForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ('status',)


class CreateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

bboard/user/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import AdvUser
from .models import user_registrated


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите тот же самый пароль еще раз')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages')

user/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import AdvUser
from .models import user_registrated


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите тот же самый пароль еще раз')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages')

bboard/application/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView

from .forms import CreateApplicationForm, ChangeStatusForm, CreateCategoryForm
from .models import Application, Category


class CreateApplicationView(CreateView, LoginRequiredMixin):
    model = Application
    template_name = 'application/create_application.html'
    form_class = CreateApplicationForm
    success_url = reverse_lazy('user:profile')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateApplicationView, self).form_valid(form)


class DeleteApplication(View, LoginRequiredMixin):
    def get(self, request, pk):
        Application.objects.get(id=pk).delete()
        return redirect(reverse_lazy('user:profile'))


class ChangeStatusView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Application
    template_name = 'application/change_status.html'
    form_class = ChangeStatusForm
    success_url = reverse_lazy('main:index')
    success_message = 'Статус изменён'


class IndexCategory(View, LoginRequiredMixin):
    def get(self, request):
        categories = Category.objects.all()
        return render(request, 'application/category.html', {'categories': categories})


class DeleteCategory(View, LoginRequiredMixin):
    def get(self, request, pk):
        Category.objects.get(id=pk).delete()
        return redirect(reverse_lazy('application:index_category'))


class CreateCategory(CreateView, LoginRequiredMixin):
    model = Category
    template_name = 'application/create_category.html'
    form_class = CreateCategoryForm
    success_url = reverse_lazy('application:index_category')

bboard/main/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render

from django.shortcuts import render
from django.template import TemplateDoesNotExist
from django.template.loader import get_template

from application.models import Application


def index(request):
    applications = Application.objects.all()
    return render(request, 'main/index.html', {'applications': applications})


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

bboard/user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView
from django.core.signing import BadSignature

from .utilities import signer
from .forms import RegisterUserForm
from .models import AdvUser
from application.models import Application


class BBLoginView(LoginView):
    template_name = 'user/login.html'


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'user/logout.html'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'user/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('user:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'user/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'user/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'user/user_is_activated.html'
    else:
        template = 'user/activation_done.html'
        user.is_activated = True
        user.is_active = True
        user.save()
    return render(request, template)


@login_required
def profile(request):
    applications = Application.objects.filter(user_id=request.user.id)
    return render(request, 'user/profile.html', {'applications': applications})

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView
from django.core.signing import BadSignature

from .utilities import signer
from .forms import RegisterUserForm
from .models import AdvUser


class BBLoginView(LoginView):
    template_name = 'user/login.html'


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'user/logout.html'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'user/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('user:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'user/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'user/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'user/user_is_activated.html'
    else:
        template = 'user/activation_done.html'
        user.is_activated = True
        user.is_active = True
        user.save()
    return render(request, template)


@login_required
def profile(request):
    return render(request, 'user/profile.html')

bboard/templates/user/activation_done.html
{% extends "layout/basic.html" %}


{% block title %} Активация выполнена {% endblock %}


{% block content %}
<h2>Активация</h2>
<p>Активация пользователя завершена</p>
<p><a href="{% url 'user:login' %}">Войти на сайт</a></p>
{% endblock %}

bboard/templates/user/bad_signature.html
{% extends "layout/basic.html" %}


{% block title %} Ошибка при активации {% endblock %}


{% block content %}
<h2>Активация</h2>
<p>Регистрация пользователя прошла неудачно.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

bboard/templates/user/login.html
{% extends "layout/basic.html" %}


{% load bootstrap4 %}


{% block title %} Вход {% endblock %}


{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
   {% csrf_token %}
   {% bootstrap_form form layout='horizontal' %}
   <input type="hidden" name="next" value="{{ next }}">
   {% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endif %}
{% endblock %}

bboard/templates/user/logout.html
{% extends "layout/basic.html" %}


{% block title %} Выход {% endblock %}


{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

bboard/templates/user/profile.html
{% extends "layout/basic.html" %}


{% load bootstrap4 %}


{% block title %} Профиль пользователя {% endblock %}


{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }} </p>
{% else %}
<p>Здравствуйте! </p>
{% endif %}
<h3>Ваши заявки</h3>
<a href="{% url 'application:create' %}">{% bootstrap_button "Создать новую заявку"%}</a>
<div class="card-deck" style="margin-top: 10px">
    {%for applic in applications%}
    <div class="card col-sm-4">
        <img class="card-img-top" src="{{ applic.image.url }}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{applic.title}}</h5>
            <p class="card-text">{{applic.text}}</p>
            <p class="card-text">Категория: {{applic.category}}</p>
            <p class="card-text">Статус: {{applic.get_status_display}}</p>
            <p class="card-text">{{applic.created_at}}</p>
            <a href="{%url 'application:delete' applic.id %}">
                <button class="btn btn-danger">Удалить</button>
            </a>
            {%if user.is_staff and applic.status == "new"%}
              <a href="{%url 'application:change_status' applic.id %}">
                <button class="btn btn-warning">Изменить статус</button>
              </a>
            {% endif %}
        </div>
    </div>
    {%endfor%}
</div>
{% endblock %}

bboard/templates/user/register_done.html
{% extends "layout/basic.html" %}


{% block title %} Регистрация завершена {% endblock %}


{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для активации</p>
{% endblock %}

bboard/templates/user/register_user.html
{% extends "layout/basic.html" %}


{% load bootstrap4 %}


{% block title %} Регистрация {% endblock %}


{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
   {% csrf_token %}
   {% bootstrap_form form layout='horizontal' %}
   {% buttons submit='Зарегистрироваться' %} {% endbuttons %}
</form>
{% endblock %}

bboard/templates/user/user_is_activated.html
{% extends "layout/basic.html" %}


{% block title %} Пользователь уже активирован {% endblock %}


{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем уже был активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}