bboard/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
    path('', include('user.urls', namespace='')),
    path('', include('application.urls', namespace=''))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
    path('', include('user.urls', namespace=''))
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/user/urls.py
from django.urls import path

from .views import *

app_name = 'user'

urlpatterns = [
   path('accounts/login', BBLoginView.as_view(), name='login'),
   path('accounts/profile/', profile, name='profile'),
   path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
   path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
   path('accounts/register/', RegisterUserView.as_view(), name='register'),
   path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
]

main/urls.py
from django.urls import path

from .views import index, other_page

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('<str:page>/', other_page, name='other'),
]

templates/layout/basic.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
  <title>{% block title %} Главная {% endblock %} - Электронная доска объявлений </title>
</head>
<body>
<div class="container-fluid">
  <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3  bg-white border-bottom box-shadow">
   <h5 class="mr-md-auto p-2">Электронная доска объявлений</h5>
   {% if user.is_authenticated %}
   <div class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Профиль</a>
       <div class="dropdown-menu">
           <a class="dropdown-item" href="{% url 'user:profile' %}">Мои объявления</a>
           <a class="dropdown-item" href="#">Изменить личные данные</a>
           <a class="dropdown-item" href="#">Изменить пароль</a>
           <div class="dropdown-divider"></div>
           <a class="dropdown-item" href="{% url 'user:logout' %}">Выйти</a>
           <div class="dropdown-divider"></div>
           <a class="dropdown-item" href="#">Удалить</a>
       </div>
   </div>
   {% else %}
   <a class="p-2 text-dark" href="{% url 'user:register' %}">Регистрация</a>
   <a class="p-2 text-dark" href="{% url 'user:login' %}">Вход</a>
   {% endif %}
</div>

  <div class="row">


      <nav class="col-md-auto nav flex-column">
          <a class="nav-link root" href="{% url 'main:index'  %}">Главная</a>
          <span class="nav-link root font-weight-bold">
              Недвижимость
          </span>
          <a class="nav-link" href="#">Жилье</a>
          <a class="nav-link" href="#">Скалады</a>
          <a class="nav-link" href="#">Квартиры</a>

          <span class="nav-link root font-weight-bold">
              Транспорт
          </span>
          <a class="nav-link" href="#">Автомобили</a>
          <a class="nav-link" href="#">Мото</a>
          <a class="nav-link" href="#">Велосипеды</a>
      </nav>


      <div class="container">
      {% bootstrap_messages %}
      {% block content %}
      {% endblock %}
      </div>


  </div>


  <footer class="mt-3 border-top">
      <small class="p-2"> &copy; Методическое пособие: Знакомство с фреймворком
          Django. 2018-2019
      </small>
  </footer>
</div>


</body>
</html>